disabled_rules:
  - trailing_comma
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing

excluded:
  - .build
  - Package.swift

identifier_name:
  min_length: 2
  excluded:
    - id
    - db
    - i
    - j

type_name:
  min_length: 2

type_body_length:
  warning: 450
  error: 600

file_length:
  warning: 700
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

function_body_length:
  warning: 100
  error: 200
