import Foundation
import GRDB
import MCP

/// Lists story theme clusters with labels, sizes, top entities, and summaries.
enum MCPGetThemesTool {
    static func run(arguments: [String: Value], database: any MCPDatabaseReader = Database.current) throws -> String {
        let limit = arguments["limit"]?.intValue ?? 20
        let query = arguments["query"]?.stringValue

        let results = try database.read { db -> [Row] in
            if let query, !query.isEmpty {
                return try Row.fetchAll(db, sql: """
                    SELECT c.cluster_id, c.label, c.size, c.summary,
                           c.top_entities_json, rank
                    FROM fts_cluster
                    JOIN clusters c ON fts_cluster.rowid = c.cluster_id
                    WHERE fts_cluster MATCH ?
                    ORDER BY rank
                    LIMIT ?
                """, arguments: [sanitizeForFTS5(query), limit])
            } else {
                return try Row.fetchAll(db, sql: """
                    SELECT cluster_id, label, size, summary, top_entities_json
                    FROM clusters
                    ORDER BY size DESC
                    LIMIT ?
                """, arguments: [limit])
            }
        }

        guard !results.isEmpty else {
            if let query {
                return "No themes found matching '\(query)'. Try a broader search or use get_themes without a query to list all themes."
            }
            return "No story themes found. Themes are generated by running the clustering pipeline in the NewsComb app."
        }

        var output: String
        if let query {
            output = "Found \(results.count) theme(s) matching '\(query)':\n\n"
        } else {
            output = "Top \(results.count) story theme(s) by size:\n\n"
        }

        for row in results {
            let clusterId: Int64 = row["cluster_id"]
            let label: String? = row["label"]
            let size: Int = row["size"]
            let summary: String? = row["summary"]
            let topEntitiesJson: String? = row["top_entities_json"]

            output += "### \(label ?? "Theme \(clusterId)") (\(size) events)\n"
            output += "Cluster ID: \(clusterId)\n"

            if let json = topEntitiesJson,
               let data = json.data(using: .utf8),
               let entities = try? JSONDecoder().decode([MCPRankedEntity].self, from: data),
               !entities.isEmpty {
                let topNames = entities.prefix(5).map { $0.label }
                output += "Top entities: \(topNames.joined(separator: ", "))\n"
            }

            if let summary, !summary.isEmpty { output += "\(summary)\n" }
            output += "\n"
        }
        return output
    }
}
